#!/usr/bin/env bash
# Changes localhost to 127.0.0.2 and adds facebook.com to 8.8.8.8
cp /etc/hosts /tmp/hosts
sed -i 's/127.0.0.1[[:space:]]*localhost/127.0.0.2 localhost/' /tmp/hosts
echo "8.8.8.8 facebook.com" >> /tmp/hosts
cat /tmp/hosts > /etc/hosts
