#!/usr/bin/env bash
# Configures localhost and facebook.com name resolution in /etc/hosts
sed -i "/127.0.0.1[[:space:]]\+localhost/d" /etc/hosts
sed -i "/127.0.0.2[[:space:]]\+localhost/d" /etc/hosts
sed -i "/8.8.8.8[[:space:]]\+facebook.com/d" /etc/hosts
echo "127.0.0.2 localhost" >> /etc/hosts
echo "8.8.8.8 facebook.com" >> /etc/hosts
